version: '3.8'

services:
  backend:
    image: docker.io/prashanth7993/zose-backend:1.0.0
    container_name: zose-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: docker.io/prashanth7993/zose-frontend:1.0.0
    container_name: zose-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always