server {
    listen 80;
    server_name zose-frontend.onrender.com;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # location /api {
    #     proxy_pass https://zose-backend.onrender.com;
    #     proxy_set_header Host Host zose-backend.onrender.com;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-   Proto $scheme;
    # }
}